Jenkins agents rename + erlang,graalvm & rust agents 🔠
redhat-cop/helm-charts pull request #93
Opened 2020-09-22 11:57 UTC by pabrahamsson

Cleaned up some legacy language around Jenkins agents and added three additional ones. I also like things in alphabetical order :capital_abcd:

2020-09-22 13:06 UTC, springdo requested changes
Looks like you need to sort the linting out @pabrahamsson  - The CT tool requires a version bump so push a change to it in the `charts/jenkins/chart.yaml` and I can smash it in!

2020-09-22 15:32 UTC, pabrahamsson commented
Thanks @springdo checks look better now

2020-09-28 10:01 UTC, springdo commented
@pabrahamsson  - cheers for that. One thing I've just noticed, the agents are all pointing to `master` we should probs move that to a release version in quickstarts. I'll smash this one in now, and shoot a PR to you afterwards though

2020-09-28 10:01 UTC, springdo approved these changes

2020-09-28 10:02 UTC, merged